<a href="https://colab.research.google.com/github/anieruth007/PRODIGY_DS_02/blob/main/Untitled14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
df = pd.read_csv("alcohol.csv")
print(df)

          Entity Code  Year  \
0    Afghanistan  AFG  2010
1    Afghanistan  AFG  2015
2    Afghanistan  AFG  2018
3        Albania  ALB  2000
4        Albania  ALB  2005
..           ...  ...   ...
989     Zimbabwe  ZWE  2000
990     Zimbabwe  ZWE  2005
991     Zimbabwe  ZWE  2010
992     Zimbabwe  ZWE  2015
993     Zimbabwe  ZWE  2018

    Total alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)
0                                                 0.21
1                                                 0.21
2                                                 0.21
3                                                 6.57
4                                                 7.65
..                                                 ...
989                                               2.46
990                                               2.77
991                                               3.93
992                                               4.92
993                                               4.67

[994 rows x 4 columns]

In [4]:
df.head()

,Entity,Code,Year,"Total alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)"
0,Afghanistan,AFG,2010,0.21
1,Afghanistan,AFG,2015,0.21
2,Afghanistan,AFG,2018,0.21
3,Albania,ALB,2000,6.57
4,Albania,ALB,2005,7.65

In [6]:
df1 = pd.DataFrame(df)
df1

,Entity,Code,Year,"Total alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)"
0,Afghanistan,AFG,2010,0.21
1,Afghanistan,AFG,2015,0.21
2,Afghanistan,AFG,2018,0.21
3,Albania,ALB,2000,6.57
4,Albania,ALB,2005,7.65
...,...,...,...,...
989,Zimbabwe,ZWE,2000,2.46
990,Zimbabwe,ZWE,2005,2.77
991,Zimbabwe,ZWE,2010,3.93
992,Zimbabwe,ZWE,2015,4.92
993,Zimbabwe,ZWE,2018,4.67

In [11]:
year_data = df.loc[df1['Year'] == 2015]
print(year_data)

          Entity      Code  Year  \
1    Afghanistan       AFG  2015
6        Albania       ALB  2015
11       Algeria       DZA  2015
16       Andorra       AND  2015
21        Angola       AGO  2015
..           ...       ...   ...
972      Vietnam       VNM  2015
977        World  OWID_WRL  2015
982        Yemen       YEM  2015
987       Zambia       ZMB  2015
992     Zimbabwe       ZWE  2015

    Total alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)
1                                                 0.21
6                                                 6.74
11                                                0.93
16                                               11.01
21                                                7.96
..                                                 ...
972                                               7.86
977                                         62.851.796
982                                                 55
987                                               6.89
992                                               4.92

[201 rows x 4 columns]

In [16]:
country_data = df[df1['Entity'] == 'India']
print(country_data)

    Entity Code  Year  \
401  India  IND  2000
402  India  IND  2005
403  India  IND  2010
404  India  IND  2015
405  India  IND  2018

    Total alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)
401                                               2.28
402                                               2.33
403                                               4.35
404                                               5.54
405                                               5.54

In [24]:
df1.rename(columns={"Total alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)" : "consumption"}, inplace=True)
print(df1)

          Entity Code  Year consumption
0    Afghanistan  AFG  2010        0.21
1    Afghanistan  AFG  2015        0.21
2    Afghanistan  AFG  2018        0.21
3        Albania  ALB  2000        6.57
4        Albania  ALB  2005        7.65
..           ...  ...   ...         ...
989     Zimbabwe  ZWE  2000        2.46
990     Zimbabwe  ZWE  2005        2.77
991     Zimbabwe  ZWE  2010        3.93
992     Zimbabwe  ZWE  2015        4.92
993     Zimbabwe  ZWE  2018        4.67

[994 rows x 4 columns]

In [63]:
highest_consumption = df1['consumption'].max()
highest_country = df1[df1['consumption'] == highest_consumption]['Entity'].iloc[0]
highest_year = df1[df1['consumption'] == highest_consumption]['Year'].iloc[0]

print(f"Highest Consumption: {highest_consumption}")
print(f"Country: {highest_country}")
print(f"Year: {highest_year}")

Highest Consumption: 98.0
Country: Libya
Year: 2010

In [57]:
df1.tail(10)

       Entity Code  Year consumption
984    Zambia  ZMB  2000       04.05
985    Zambia  ZMB  2005         3.9
986    Zambia  ZMB  2010        5.43
987    Zambia  ZMB  2015        6.89
988    Zambia  ZMB  2018        6.54
989  Zimbabwe  ZWE  2000        2.46
990  Zimbabwe  ZWE  2005        2.77
991  Zimbabwe  ZWE  2010        3.93
992  Zimbabwe  ZWE  2015        4.92
993  Zimbabwe  ZWE  2018        4.67

In [62]:
df1['consumption'] = pd.to_numeric(df1['consumption'], errors='coerce')
mean_consumption = df1['consumption'].dropna().mean()
print(f"Mean Consumption: {mean_consumption}")

Mean Consumption: 7.027699784017278